### ISSUE TITLE
💄 revise style rules, auto linting settings, etc

### ISSUE THREAD

**Issue by lucas-labs** [lucas-labs/pest#15]
Right now we are using `ruff` for some linting rules and `autopep8` for formatting. 

`ruff` has its own formatter, which is pretty good, but is lacking an option to preserve string normalization. So, just for now, until PR astral-sh/ruff#8822 is merged, we will use `black` with `--skip-string-normalization` option.

### why?

I prefeer using `flake8-quotes` with ruff for normalizing string quotes, as it allows the following configuration, which I personally prefeer:

```toml
[flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "single"
```
